In [1]:
import pandas as pd

In [2]:
roll = pd.Series([1, 2, 3, 4, 5])
name = pd.Series(['Sia', 'Ravi', 'Geet', 'Ajeenkya', 'Avinash'])
marks = pd.Series([85, 67, 59, 40, 90])

In [4]:
df = pd.DataFrame({
    'id': roll,
    'name': name,
    'marks': marks
})

In [5]:
df

   id      name  marks
0   1       Sia     85
1   2      Ravi     67
2   3      Geet     59
3   4  Ajeenkya     40
4   5   Avinash     90

In [8]:
df.ndim

2

In [9]:
df.shape

(5, 3)

In [10]:
df.size

15

In [11]:
df.columns

Index(['id', 'name', 'marks'], dtype='object')

In [14]:
"""
url --> https://mitu.co.in/dataset

download all the datasets starting with student *
put them in the same file folder as ur current wrking directory

""";

In [15]:
pwd

'C:\\Users\\Hp'

In [16]:
df = pd.read_csv("student.csv")

In [17]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [18]:
df.shape

(10, 5)

In [19]:
df.columns

Index(['roll', 'name', 'class', 'marks', 'age'], dtype='object')

In [20]:
df.size

50

In [21]:
# student1.csv

In [22]:
df = pd.read_csv("student1.csv")

In [23]:
df

    1     anil  TE  56.77  22
0   2     amit  TE  59.77  21
1   3   aniket  BE  76.88  19
2   4  ajinkya  TE  69.66  20
3   5     asha  TE  63.28  20
4   6   ayesha  BE  49.55  20
5   7     amar  BE  65.34  19
6   8    amita  BE  68.33  23
7   9     amol  TE  56.75  20
8  10    anmol  BE  78.66  21

In [24]:
df.shape

(9, 5)

In [25]:
df.size

45

In [26]:
df.columns

Index(['1', 'anil', 'TE', '56.77', '22'], dtype='object')

In [27]:
col = ['roll', 'name', 'class', 'marks', 'age']

In [28]:
df = pd.read_csv('student1.csv', names = col)
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21

In [29]:
# student3.csv

In [30]:
df = pd.read_csv("student3.csv")

In [31]:
df

    roll     name class  marks    age
0      1     anil    TE   56.77  22.0
1      2     amit    TE   59.77  21.0
2      3   aniket    BE   76.88  19.0
3      4  ajinkya    TE   69.66  20.0
4      5     asha    TE   63.28   NaN
5      6   ayesha    BE     NaN  20.0
6      7     amar    BE   65.34  19.0
7      8    Amita    be   68.33  23.0
8      9     amol    TE   56.75  20.0
9      9     amol    TE   56.75  20.0
10    10    anmol    BE   78.66   NaN
11    11   surbhi    TE     NaN  23.0
12    12    Sujay    TE   74.12  22.0
13    13  subhash    be   88.45  21.0
14    14   sachin   NaN   59.33  21.0
15    15  shalini    TE   63.45  20.0

In [32]:
df.shape

(16, 5)

In [33]:
df.size

80

In [34]:
df.columns

Index(['roll', 'name', 'class', 'marks ', 'age'], dtype='object')

In [35]:
df = pd.read_csv("student3.tsv")

In [36]:
df

  roll\tname\tclass\tmarks\tage
0        1\tanil\tTE\t56.77\t22
1        2\tamit\tTE\t59.77\t21
2      3\taniket\tBE\t76.88\t19
3     4\tajinkya\tTE\t69.66\t20
4        5\tasha\tTE\t63.28\t20
5      6\tayesha\tBE\t49.55\t20
6        7\tamar\tBE\t65.34\t19
7       8\tamita\tBE\t68.33\t23
8        9\tamol\tTE\t56.75\t20
9      10\tanmol\tBE\t78.66\t21

In [37]:
df = pd.read_csv('student3.tsv', sep = '\t')

In [38]:
df

   roll     name class  marks  age
0     1     anil    TE  56.77   22
1     2     amit    TE  59.77   21
2     3   aniket    BE  76.88   19
3     4  ajinkya    TE  69.66   20
4     5     asha    TE  63.28   20
5     6   ayesha    BE  49.55   20
6     7     amar    BE  65.34   19
7     8    amita    BE  68.33   23
8     9     amol    TE  56.75   20
9    10    anmol    BE  78.66   21